package br.com.aminfoloc.model;
// Generated 16/06/2011 14:08:29 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {

     private Integer idCliente;
     private String nome;
     private String bairro;
     private String telefone;
     private String endereco;
     private String cidade;
     private String celular;
     private String email;
     private Byte ativo;
     private Set<Locacao> locacaos = new HashSet<Locacao>(0);

    public Cliente() {
    }

    public Cliente(String nome, String bairro, String telefone, String endereco, String cidade, String celular, String email, Byte ativo, Set<Locacao> locacaos) {
       this.nome = nome;
       this.bairro = bairro;
       this.telefone = telefone;
       this.endereco = endereco;
       this.cidade = cidade;
       this.celular = celular;
       this.email = email;
       this.ativo = ativo;
       this.locacaos = locacaos;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Byte getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Byte ativo) {
        this.ativo = ativo;
    }
    public Set<Locacao> getLocacaos() {
        return this.locacaos;
    }
    
    public void setLocacaos(Set<Locacao> locacaos) {
        this.locacaos = locacaos;
    }




}


