package br.com.aminfoloc.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Filme generated by hbm2java
 */
public class Filme  implements java.io.Serializable {


     private Integer idFilme;
     private Genero genero;
     private String titulo;
     private Boolean locado;
     private String tituloOriginal;
     private Set<Locacao> locacaos = new HashSet<Locacao>(0);

    public Filme() {
    }

    public Filme(Genero genero, String titulo, Boolean locado, String tituloOriginal, Set<Locacao> locacaos) {
       this.genero = genero;
       this.titulo = titulo;
       this.locado = locado;
       this.tituloOriginal = tituloOriginal;
       this.locacaos = locacaos;
    }
   
    public Integer getIdFilme() {
        return this.idFilme;
    }
    
    public void setIdFilme(Integer idFilme) {
        this.idFilme = idFilme;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Boolean getLocado() {
        return this.locado;
    }
    
    public void setLocado(Boolean locado) {
        this.locado = locado;
    }
    public String getTituloOriginal() {
        return this.tituloOriginal;
    }
    
    public void setTituloOriginal(String tituloOriginal) {
        this.tituloOriginal = tituloOriginal;
    }
    public Set<Locacao> getLocacaos() {
        return this.locacaos;
    }
    
    public void setLocacaos(Set<Locacao> locacaos) {
        this.locacaos = locacaos;
    }




}


