package br.com.aminfoloc.model;
// Generated 16/06/2011 14:08:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String descricao;
     private Set<Filme> filmes = new HashSet<Filme>(0);

    public Genero() {
    }

    public Genero(String descricao, Set<Filme> filmes) {
       this.descricao = descricao;
       this.filmes = filmes;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set<Filme> getFilmes() {
        return this.filmes;
    }
    
    public void setFilmes(Set<Filme> filmes) {
        this.filmes = filmes;
    }




}


