package br.com.aminfoloc.model;
// Generated 16/06/2011 14:08:29 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Locacao generated by hbm2java
 */
public class Locacao  implements java.io.Serializable {


     private Integer idLocacao;
     private Filme filme;
     private Cliente cliente;
     private Date dataHoraLocacao;
     private Byte finalizarLocacao;
     private Date dataHoraDevolucao;

    public Locacao() {
    }

    public Locacao(Filme filme, Cliente cliente, Date dataHoraLocacao, Byte finalizarLocacao, Date dataHoraDevolucao) {
       this.filme = filme;
       this.cliente = cliente;
       this.dataHoraLocacao = dataHoraLocacao;
       this.finalizarLocacao = finalizarLocacao;
       this.dataHoraDevolucao = dataHoraDevolucao;
    }
   
    public Integer getIdLocacao() {
        return this.idLocacao;
    }
    
    public void setIdLocacao(Integer idLocacao) {
        this.idLocacao = idLocacao;
    }
    public Filme getFilme() {
        return this.filme;
    }
    
    public void setFilme(Filme filme) {
        this.filme = filme;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getDataHoraLocacao() {
        return this.dataHoraLocacao;
    }
    
    public void setDataHoraLocacao(Date dataHoraLocacao) {
        this.dataHoraLocacao = dataHoraLocacao;
    }
    public Byte getFinalizarLocacao() {
        return this.finalizarLocacao;
    }
    
    public void setFinalizarLocacao(Byte finalizarLocacao) {
        this.finalizarLocacao = finalizarLocacao;
    }
    public Date getDataHoraDevolucao() {
        return this.dataHoraDevolucao;
    }
    
    public void setDataHoraDevolucao(Date dataHoraDevolucao) {
        this.dataHoraDevolucao = dataHoraDevolucao;
    }




}


